/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
 #define RCC_BASE_ADDR                   0x40023800UL
 #define RCC_CFGR_REG_OFFSET     0x08UL
 #define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)
 #define GPIOA_BASE_ADDR                0x40020000UL
 uint32_t *pRccCfgrReg =  (uint32_t*) RCC_CFGR_REG_ADDR;

int main(void)
{
	 *pRccCfgrReg &= ~(0x3 << 21); // Clear 21 and 22 bit positions
	 *pRccCfgrReg |= (1 << 25);
	 *pRccCfgrReg |= (1 << 26);
	 uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	 *pRCCAhb1Enr |= ( 1 << 0); // Enable GPIOA peripheral clock
    /* Loop forever */
	 uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	 *pGPIOAModeReg &= ~( 0x3 << 16); //clear
	 *pGPIOAModeReg |= ( 0x2 << 16);  //set
	 uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	 *pGPIOAAltFunHighReg &= ~( 0x0f << 0);
	for(;;);
}
